### ISSUE TITLE
feat: cicd 기능 구현

### ISSUE THREAD

**Issue by teabear12** [Hanghae99-FinalProject-Buycation/BE-Buycation#38]
## Description
feat: cicd 기능 구현

## Todo
- [ ] AWS EC2 설정 추가
- [ ] AWS S3 버킷 생성
- [ ] AWS CodeDeploy 설정
- [ ] AppSpec 파일 생성
- [ ] build.gradle  자동 plain jar 생성 방지 추가
- [ ]  start.sh 파일 생성
- [ ] stop.sh 파일 생성

## Etc
없음
