### ISSUE TITLE
채팅 기능 

### ISSUE THREAD

**Issue by syckor** [Hanghae99-FinalProject-Buycation/BE-Buycation#79]
## Description
모임 참가자들을 위한 채팅방 생성

## Todo
- [ ] 모임 생성했을 때 자동 채팅방 생성
- [ ] 모임 참가했을 때 자동 채팅방 참여
- [ ] 새로운 채팅 생성시 알림 기능

## Etc
기타사항
